version: '3.8'

services:
  credit-platform:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: bay-area-credit-platform
    
    # 环境变量
    environment:
      - NODE_ENV=production
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
